---
# Inventory pour environnement STAGING
all:
  children:
    staging:
      children:
        web:
          hosts:
            web-server-staging:
              ansible_host: 192.168.1.211
              ansible_user: jordan
        db:
          hosts:
            db-server-staging:
              ansible_host: 192.168.1.212
              ansible_user: jordan
      vars:
        env: staging
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
