---
all:
  children:
    web:
      hosts:
        web-server:
          ansible_host: 192.168.1.201
          ansible_user: jordan
    db:
      hosts:
        db-server:
          ansible_host: 192.168.1.202
          ansible_user: jordan
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
