---
- name: Collecter les facts de tous les serveurs
  hosts: all
  gather_facts: true
  tasks: []

- name: Configuration des serveurs Web
  hosts: web
  become: true
  roles:
    - common
    - security
    - web

- name: Configuration des serveurs DB
  hosts: db
  become: true
  roles:
    - common
    - security
    - db
