---
- name: Collecter les facts de tous les serveurs
  hosts: all
  gather_facts: true
  tasks: []

- name: Configuration des serveurs Web
  hosts: web
  roles:
    - common
    - web

- name: Configuration des serveurs DB
  hosts: db
  roles:
    - common
    - db
